/* generated by dia/codegen.py */
class Trens 
{
public:
	void atualiza_posicao ();
	int id;
	int linha_id;
	int plataforma_atual_id;
	int conexao_atual_id;
	float velocidade_atual;
	float percorrido;
private:
	GLfloat cor;
};

class Conexoes 
{
public:
	void desenha ();
	int id;
	int de_painel_id;
	int ate_painel_id;
	int distancia;
	int com_defeito;
private:
	GLfloat cor;
};



class Paineis 
{
public:
	void set_tempo (int segundos);
	void desenha ();
	int id;
	int linha_id;
	int posX;
	int posY;
private:
	void set_pos (int plataforma_id);
	void atualiza_tempo_tela ();
	int horas;
	int minutos;
	int segundos;
	GLfloat cor;
};

class Linhas 
{
public:
	void desenha_legenda ();
	int id;
	char * nome;
	Conexoes conexoes[];
private:
	GLfloat cor;
};

