/* generated by dia/codegen.py */
/*(NULL)*/
class Trens 
{
public:
	void atualiza_posicao ();
	int id;
	int linha_id;
	int thread_id;
	int plataforma_atual_id;
	int conexao_atual_id;
	float velocidade_atual;
	float percorrido;
private:
	GLcor cor;
};

/*(NULL)*/
class Conexoes 
{
public:
	void inicializa (int de_plat_id,
	                 int ate_plat_id,
	                 GLcor c);
	void desenha ();
	int id;
	int de_plataforma_id;
	int ate_plataforma_id;
	int distancia;
	int com_defeito;
private:
	GLcor cor;
};

class Plataformas 
{
public:
	void inicializa (char * n,
	                 int x,
	                 int y);
	void desenha ();
	int id;
	char * nome;
	int posX;
	int posY;
	int paineis_ocupados;
	int com_defeito;
};

/*(NULL)*/
class Paineis 
{
public:
	void inicializa (int plat_id,
	                 int linha_id,
	                 int ocupar_painel,
	                 GLcor c);
	void desenha ();
	void procura_prox_trem ();
	void set_tempo (int segundos);
	int id;
	int plataforma_id;
	int linha_id;
	int thread_id;
	int proximo_trem_id;
	int posX;
	int posY;
private:
	void atualiza_tempo_tela ();
	int horas;
	int minutos;
	int segundos;
	GLcor cor;
};

/*(NULL)*/
class Linhas 
{
public:
	void inicializa (char * n,
	                 GLcor c);
	void add_conexao (int de_plat_id,
	                  int ate_plat_id);
	void desenha_legenda ();
	int id;
	char * nome;
	Conexoes * conexoes;
private:
	GLcor cor;
};

